### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by hamedhosseini143** [saeedghezelarsalan/Digikala-Ecommerce#1]
when yarn run dev have error

error - Error: connect ECONNREFUSED 127.0.0.1:3001
error - Error: connect ECONNREFUSED 127.0.0.1:3001
error - Error: connect ECONNREFUSED 127.0.0.1:3001

**Comment by saeedghezelarsalan** [comment]
This error is because you did not run the data file that Jason Server also has.
To run the data, you must first enter the Data file with the following code : 

1) Cd Data
2) npm run start or yarn run start
