### ISSUE TITLE
Error in first run

### ISSUE THREAD

**Issue by javadgt** [saeedghezelarsalan/Digikala-Ecommerce#2]
1. i clone this repository
2. go to directory
3. npm install next
4. npm run dev

Error Message : 

```
Error: connect ECONNREFUSED 127.0.0.1:3001

This error happened while generating the page. Any console logs will be displayed in the terminal window.

Call Stack
<unknown> (Error: connect ECONNREFUSED
127.0.0.1 (3001)
TCPConnectWrap.afterConnect [as oncomplete]
node:net (1247:16)
```

**Comment by saeedghezelarsalan** [comment]
This error is because you did not run the data file that Jason Server also has.
To run the data, you must first enter the Data file with the following code :

Cd Data
npm run start

**Comment by javadgt** [comment]
thanks fixed
